Fix SyntaxError in analyze() caused by unclosed try/except
Removes the broken try/except wrapper added in bbd4a58 that caused:
SyntaxError: expected 'except' or 'finally' block